#ifndef VSOMEIP_EXAMPLES_MULTIPLE_SERVICE_IDS_HPP
#define VSOMEIP_EXAMPLES_MULTIPLE_SERVICE_IDS_HPP

// Speed Service
#define SPEED_SERVICE_ID       0x0001
#define SPEED_INSTANCE_ID      0x0001
#define SPEED_METHOD_ID        0x0001

#define SPEED_EVENT_ID         0x0001
#define SPEED_GET_METHOD_ID    0x1001
#define SPEED_SET_METHOD_ID    0x1002

#define SPEED_EVENTGROUP_ID    0x0001

// Distance Service
#define DISTANCE_SERVICE_ID       0x0002
#define DISTANCE_INSTANCE_ID      0x0001
#define DISTANCE_METHOD_ID        0x0001

#define DISTANCE_EVENT_ID         0x0001
#define DISTANCE_GET_METHOD_ID    0x2001
#define DISTANCE_SET_METHOD_ID    0x2002

#define DISTANCE_EVENTGROUP_ID    0x0001

#endif // VSOMEIP_EXAMPLES_MULTIPLE_SERVICE_IDS_HPP